M48
; DRILL file {KiCad 7.0.8} date Sun Jun  1 22:45:11 2025
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-06-01T22:45:11-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.8
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.800
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.900
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C2.200
%
G90
G05
T1
X176.245Y-52.0
X176.245Y-57.0
T2
X144.345Y-50.3
X144.345Y-53.3
T3
X145.0Y-43.8
X145.0Y-71.8
X178.2Y-43.8
X178.2Y-71.8
T0
M30
